### ISSUE TITLE
Using .pop() to remove items from the taglist breaks if you delete a tag at the beginning or middle

### ISSUE THREAD

**Issue by jonrundle** [bitmazk/jquery-typeahead-tagging#1]
When there are multiple tags and you delete one from the beginning or middle of the list it works visually but the comma separated value in the hidden input are incorrect. It only removes the last one. By investigating further, realized it's because of .pop(). Should use .splice() instead. Something like this: $.tagged.current_taglist.splice(tag_index,1); should work better. Solution found by @andrewprocter

**Comment by andrewprocter** [comment]
Here's the whole updated delete_tag function. Also moved the tag_index to it's own line:

```
function delete_tag($TAGGED_tag) {
        // removes a tag and updates the hidden input 
        var removed_tag = $TAGGED_tag.clone().children().remove().end().text();
        var tag_index = $.tagged.current_taglist.indexOf(removed_tag);
        $.tagged.current_taglist.splice(tag_index,1);
        $TAGGED_tag.remove();
        sync_input();
 }
```
