### ISSUE TITLE
Plugin is not multi-instance ready

### ISSUE THREAD

**Issue by davoscript** [bitmazk/jquery-typeahead-tagging#4]
If you use the plugin in more than one element in the same HTML document, the last instance overrides the properties of the 1st instance.

I'll try to collaborate with the code if I find a fix.

**Comment by dkaufhold** [comment]
Yeah, development on this plugin unfortunately didn't leave the early stages. So it would be awesome, if you like to build upon that 👍

**Comment by davoscript** [comment]
Hello @dkaufhold, I made a pull request to try to fix this, it changes the plugin code structure but it's working with multiple instances. I'd love to hear your comments about it.

Best!

**Comment by dkaufhold** [comment]
Sorry, that it took a little while to respond.
Looks really good.
Thanks for putting in the work, @davoscript
